version: '3.8'

services:
  fastapi:
    build:
      context: .
    container_name: fastapi_dev
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app  # Mount the app directory from your local machine into the container
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - fastapi_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge
